<div class="col2-set">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Contact Information') ?></h3>
                <a class="janrain_capture_anchor" href="<?php echo Mage::getUrl('capture/api/profile'); ?>"><?php echo $this->__('Edit') ?></a>
            </div>
            <div class="box-content">
                <p>
                    <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
                    <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
                </p>
            </div>
        </div>
    </div>
    <?php if ($this->isNewsletterEnabled()): ?>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Newsletters') ?></h3>
                    <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
                </div>
                <div class="box-content">
                    <p>
                        <?php if ($this->getIsSubscribed()): ?>
                            <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                        <?php else: ?>
                            <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                        <?php endif; ?>
                    </p>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
